global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'web_service'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']